apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: peakblockfrontend 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: peakblockfrontend 
    spec:
      containers:
        - name: peakblockfrontend 
          image: cohub.azurecr.io/peakblockfrontend
          ports:
          - containerPort: 5000